export const SYNONYMS: Record<string, string[]> = {
  banana: ['banana','bananas','plantain'],
  apple: ['apple','apples','gala','fuji'],
  avocado: ['avocado','avocados'],
  onion: ['onion','onions','yellow onion','red onion'],
  tomato: ['tomato','tomatoes','roma','cherry tomato'],
  garlic: ['garlic','clove','garlic clove'],
  rice: ['rice','white rice','brown rice','jasmine'],
  pasta: ['pasta','spaghetti','penne','noodles'],
  'chicken breast': ['chicken','chicken breast','breast'],
  tofu: ['tofu','firm tofu','silken tofu'],
  egg: ['egg','eggs'],
  spinach: ['spinach','leafy greens'],
  'bell pepper': ['bell pepper','pepper','capsicum'],
  carrot: ['carrot','carrots'],
  potato: ['potato','potatoes','russet','yukon gold'],
  broccoli: ['broccoli','broccolini'],
  mushroom: ['mushroom','mushrooms'],
  oats: ['oats','oatmeal','rolled oats'],
  milk: ['milk','whole milk','2% milk','dairy milk'],
  yogurt: ['yogurt','yoghurt','greek yogurt'],
  cheddar: ['cheddar','cheese','cheddar cheese'],
  tortilla: ['tortilla','tortillas','wrap'],
  'canned beans': ['beans','black beans','pinto beans','canned beans'],
  'canned tuna': ['tuna','canned tuna'],
  'soy sauce': ['soy sauce','shoyu']
}
